<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Pool</label><select class="form-select" name="id_kompetisi_tanding" required><?php foreach (($poolOptions ?? []) as $pool) : ?><option value="<?= esc((string) $pool->id_kompetisi_tanding) ?>" <?= (isset($row) && (int) $row->id_kompetisi_tanding === (int) $pool->id_kompetisi_tanding) ? 'selected' : '' ?>><?= esc(($pool->nama_kategori_usia ?? '-') . ' / ' . ($pool->label ?? '-') . ' / Pool ' . ($pool->nomor_pool ?? '-')) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="form-label">Babak</label><input class="form-control" name="babak" value="<?= esc($row->babak ?? '') ?>" required></div>
    <div class="col-md-3"><label class="form-label">Nomor Pertandingan</label><input class="form-control" type="number" name="nomor_pertandingan" value="<?= esc((string) ($row->nomor_pertandingan ?? 0)) ?>" required></div>
    <div class="col-md-4"><label class="form-label">Atlet Merah</label><select class="form-select" name="id_atlet_merah"><option value="">-</option><?php foreach (($pesertaOptions ?? []) as $peserta) : ?><option value="<?= esc((string) $peserta->id_peserta_tanding) ?>" <?= (isset($row) && (int) ($row->id_atlet_merah ?? 0) === (int) $peserta->id_peserta_tanding) ? 'selected' : '' ?>><?= esc(($peserta->nama_pendaftar ?? '-') . ' - ' . ($peserta->nama_kontingen ?? '-')) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label">Atlet Biru</label><select class="form-select" name="id_atlet_biru"><option value="">-</option><?php foreach (($pesertaOptions ?? []) as $peserta) : ?><option value="<?= esc((string) $peserta->id_peserta_tanding) ?>" <?= (isset($row) && (int) ($row->id_atlet_biru ?? 0) === (int) $peserta->id_peserta_tanding) ? 'selected' : '' ?>><?= esc(($peserta->nama_pendaftar ?? '-') . ' - ' . ($peserta->nama_kontingen ?? '-')) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label">Nomor Selanjutnya</label><input class="form-control" type="number" name="nomor_pertandingan_selanjutnya" value="<?= esc((string) ($row->nomor_pertandingan_selanjutnya ?? '')) ?>"></div>
    <div class="col-md-4"><label class="form-label">Jenis Kemenangan</label><input class="form-control" name="jenis_kemenangan" value="<?= esc($row->jenis_kemenangan ?? '') ?>"></div>
    <div class="col-md-8"><label class="form-label">Keterangan</label><input class="form-control" name="keterangan" value="<?= esc($row->keterangan_pertandingan ?? $row->keterangan ?? '') ?>"></div>
</div>
