<?php if ($this->agent->is_mobile()) : ?>
	<table width="100%" class="table text-sm" id="tabelKompetisiTanding">
		<thead>
			<tr>
				<th><?= lang('no') ?></th>
				<th><?= lang('kategori_tanding') ?></th>
				<th><?= lang('nomor_pool') ?></th>
				<th class="not-mobile"><?= lang('jumlah_peserta') ?></th>
				<th class="none"><?= lang('max_peserta') ?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($data_kompetisi_tanding as $kompetisi_tanding) : ?>
				<tr>
					<td></td>
					<td class="align-middle">
						<a class="mb-0 text-wrap text-capitalize">
							<?= $kompetisi_tanding->nama_kategori_usia . '<br>' . $kompetisi_tanding->jenis_kelamin.' - '.$kompetisi_tanding->label ?>
						</a>
					</td>
					<td class="align-middle text-end"><?= $kompetisi_tanding->nomor_pool ?></td>
					<td class="align-middle text-end"><?= $kompetisi_tanding->jumlah_peserta_tanding ?></td>
					<td class="align-middle text-capitalize"><?= $kompetisi_tanding->max_peserta ?></td>
					<td class="align-middle text-end">
						<?php $this->load->view('shared_components/kompetisi_tanding/tombol_tabel', ['data' => $kompetisi_tanding]) ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<script>
		$(document).ready(function() {
			if ($('#tabelKompetisiTanding').length != 0) {
				$('#tabelKompetisiTanding').DataTable({
					dom: 'Bfrtip',
					"language": {
						"paginate": {
							"next": ">",
							"previous": "<"
						}
					},
					'autoWidth': false,
					"columnDefs": [{
							"width": "10%",
							"targets": -1
						},
						{
							className: 'dtr-control text-center py-3',
							orderable: false,
							targets: 0,
							width: '10%'
						},
						{
							orderable: false,
							width: '10%',
							target: -1
						}
					],
					'paging': true,
					'searching': true,
					'ordering': true,
					'info': true,
					'responsive': true
				})
			}

		});
	</script>

<?php else : ?>
	<table width="100%" class="table" id="tabelKompetisiTanding">
		<thead>
			<tr>
				<th class="no-export"></th>
				<th><?= lang('kategori_usia') ?></th>
				<th class="not-mobile"><?= lang('jenis_kelamin') ?></th>
				<th class="not-mobile"><?= lang('kelas') ?></th>
				<th class="not-mobile"><?= lang('nomor_pool') ?></th>
				<th class="not-mobile text-wrap"><?= lang('jumlah_peserta') ?></th>
				<th class="not-mobile text-wrap"><?= lang('jumlah_peserta_lunas') ?></th>
				<th class="not-mobile text-wrap"><?= lang('max_peserta') ?></th>
				<th class="no-export"></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($data_kompetisi_tanding as $kompetisi_tanding) : ?>
				<tr>
					<td></td>
					<td class="align-middle">
						<a class="mb-0 text-wrap text-capitalize"><?= $kompetisi_tanding->nama_kategori_usia ?></a>
					</td>
					<td class="align-middle text-capitalize"><?= $kompetisi_tanding->jenis_kelamin ?></td>
					<td class="align-middle text-center"><?= $kompetisi_tanding->label ?></td>
					<td class="align-middle text-end"><?= $kompetisi_tanding->nomor_pool ?></td>
					<td class="align-middle text-end"><?= $kompetisi_tanding->jumlah_peserta_tanding ?></td>
					<td class="align-middle text-end"><?= $kompetisi_tanding->jumlah_peserta_tanding_lunas ?></td>
					<td class="align-middle text-capitalize text-end"><?= $kompetisi_tanding->max_peserta ?></td>
					<td class="align-middle text-end">
						<?php $this->load->view('shared_components/kompetisi_tanding/tombol_tabel', ['data' => $kompetisi_tanding]) ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<script>
		$(document).ready(function() {
			if ($('#tabelKompetisiTanding').length != 0) {
				$('#tabelKompetisiTanding').DataTable({
					dom: 'Bfrtip',
					buttons: [{
							extend: 'searchPanes',
							config: {
								cascadePanes: true
							}
						},
						'searchBuilder',
						{
							extend: 'colvis',
							collectionLayout: 'fixed columns',
							collectionTitle: 'Column visibility control'
						},
						{
							extend: 'pdfHtml5',
							title: 'Daftar Pool Tanding',
							messageTop: '<?= get_instance()->get_setting('event_name') ?>',
							messageBottom: 'generated by <?= $this->config->item('brand_name')?>',
							filename: 'Daftar Pool Tanding - <?= get_instance()->get_setting('event_name') ?>',
							orientation: 'landscape',
							pageSize: 'A4',
							exportOptions: {
								columns: ':visible:not(.no-export)'
							}
						},
						{
							extend: 'excelHtml5',
							filename: 'Daftar Pool Tanding - <?= get_instance()->get_setting('event_name') ?>',
							exportOptions: {
								columns: ':visible:not(.no-export)'
							}
						},
						{
							extend: 'print',
							filename: 'Daftar Pool Tanding - <?= get_instance()->get_setting('event_name') ?>',
							exportOptions: {
								columns: ':visible:not(.no-export)'
							},
							customize: function(win) {
								$(win.document.body)
									.prepend(
										`<?php
											$this->load->view(
												'print/components/header',
												['header_title' => 'Daftar Pool Tanding', 'header_subtitle' => get_instance()->get_setting('event_name')],
												FALSE
											);
											?>`
									);

								$(win.document.body).find('h1').remove();

								$(win.document.body).find('table').css('width', '95%')
									.addClass('mx-auto');

								$(win.document.body).find('table')
									.addClass('table-striped');

								$(win.document.body).find('thead')
									.addClass('table-dark');

								$(win.document.body).find('th').addClass('text-wrap');

								$(win.document.body).find('th').first().css('width', '20%');

								$table_row = $(win.document.body).find('tbody tr');

								$.each($table_row, function(i, v) {
									$(v).find('td').first().addClass('text-wrap');
								});
							}
						}
					],
					'autoWidth': false,
					"columnDefs": [{
							"width": "10%",
							"targets": -1
						},
						{
							className: 'dtr-control text-center py-3',
							orderable: false,
							targets: 0,
							width: '10%'
						},
						{
							width: '20%',
							target: 1
						},
						{
							orderable: false,
							width: '10%',
							target: -1
						},
						{
							width: '10%',
							target: -2
						},
						{
							width: '10%',
							target: -3
						},
						{
							width: '10%',
							target: -4
						}
					],
					'paging': true,
					'searching': true,
					'ordering': true,
					'info': true,
					'responsive': true
				})
			}

		});
	</script>
<?php endif; ?>