<?= $this->extend('layouts/admin') ?>

<?= $this->section('content') ?>
<div class="row g-3 mb-4">
    <div class="col-md-6 col-xl-4">
        <div class="admin-card h-100"><div class="card-body"><div class="muted-copy small mb-1">Seni Pool Belum Dijadwalkan</div><div class="display-6 fw-bold text-danger"><?= esc((string) ($count_seni_pool_belum_dijadwalkan ?? 0)) ?></div></div></div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="admin-card h-100"><div class="card-body"><div class="muted-copy small mb-1">Seni Battle Belum Dijadwalkan</div><div class="display-6 fw-bold text-warning"><?= esc((string) ($count_seni_battle_belum_dijadwalkan ?? 0)) ?></div></div></div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="admin-card h-100"><div class="card-body"><div class="muted-copy small mb-1">Mismatch Sistem Penampilan</div><div class="display-6 fw-bold text-admin-brand"><?= esc((string) ($count_mismatch_sistem_penampilan ?? 0)) ?></div></div></div>
    </div>
</div>
<div class="admin-card mb-4"><div class="card-header pb-0 border-bottom-0 bg-transparent px-0"><h6 class="card-title">Pool Belum Dijadwalkan</h6></div><div class="card-body px-0"><div class="admin-table-wrap"><div class="table-shell admin-table-scroller"><table class="table admin-table align-middle mb-0"><thead><tr><th>Pool</th><th>Seni</th><th>Kategori</th><th>Kontingen</th></tr></thead><tbody><?php foreach (($data_penampilan_seni_pool_belum_dijadwalkan ?? []) as $row) : ?><tr><td><?= esc((string) ($row->nomor_pool ?? '-')) ?></td><td><?= esc(($row->nama_seni ?? '-') . ' / ' . ($row->jenis_seni ?? '-')) ?></td><td><?= esc(($row->nama_kategori_usia ?? '-') . ' ' . ($row->jenis_kelamin ?? '')) ?></td><td class="text-uppercase"><?= esc($row->nama_kontingen ?? '-') ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php if (empty($data_penampilan_seni_pool_belum_dijadwalkan ?? [])) : ?><div class="text-center muted-copy py-4">Tidak ada pool yang belum dijadwalkan.</div><?php endif; ?></div></div>
<div class="admin-card mb-4"><div class="card-header pb-0 border-bottom-0 bg-transparent px-0"><h6 class="card-title">Battle Belum Dijadwalkan</h6></div><div class="card-body px-0"><div class="admin-table-wrap"><div class="table-shell admin-table-scroller"><table class="table admin-table align-middle mb-0"><thead><tr><th>No. Battle</th><th>Babak</th><th>Seni</th><th>Kontingen</th></tr></thead><tbody><?php foreach (($data_battle_seni_belum_dijadwalkan ?? []) as $row) : ?><tr><td><?= esc((string) ($row->nomor_battle ?? '-')) ?></td><td><?= esc($row->babak ?? '-') ?></td><td><?= esc(($row->nama_seni ?? '-') . ' / ' . ($row->jenis_seni ?? '-')) ?></td><td class="text-uppercase"><?= esc(($row->nama_kontingen_merah ?? '-') . ' vs ' . ($row->nama_kontingen_biru ?? '-')) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php if (empty($data_battle_seni_belum_dijadwalkan ?? [])) : ?><div class="text-center muted-copy py-4">Tidak ada battle yang belum dijadwalkan.</div><?php endif; ?></div></div>
<div class="admin-card"><div class="card-header pb-0 border-bottom-0 bg-transparent px-0"><h6 class="card-title">Mismatch Sistem Penampilan</h6></div><div class="card-body px-0"><div class="admin-table-wrap"><div class="table-shell admin-table-scroller"><table class="table admin-table align-middle mb-0"><thead><tr><th>Nomor Partai</th><th>Arena</th><th>Battle</th><th>Pool</th></tr></thead><tbody><?php foreach (($data_penampilan_seni_tidak_sesuai_sistem_penampilan ?? []) as $row) : ?><tr><td><?= esc((string) ($row->nomor_partai ?? '-')) ?></td><td><?= esc($row->nama_gelanggang ?? '-') ?></td><td><?= esc(($row->nama_seni_battle ?? '-') . ' / ' . ($row->sistem_penampilan_battle ?? '-')) ?></td><td><?= esc(($row->nama_seni_pool ?? '-') . ' / ' . ($row->sistem_penampilan_pool ?? '-')) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php if (empty($data_penampilan_seni_tidak_sesuai_sistem_penampilan ?? [])) : ?><div class="text-center muted-copy py-4">Tidak ada mismatch sistem penampilan.</div><?php endif; ?></div></div>
<?= $this->endSection() ?>
