<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<section class="admin-card mb-4"><div class="d-flex justify-content-between align-items-center gap-3 mb-4"><div><p class="eyebrow mb-1">Pool Tanding</p><h3 class="section-title h4 mb-0"><?= esc(($row->label ?? '-') . ' Pool ' . ($row->nomor_pool ?? '-')) ?></h3></div><a class="btn btn-outline-secondary rounded-pill" href="<?= base_url('admin/sekretariat/pool-tanding') ?>">Kembali</a></div><form method="post" action="<?= base_url('admin/sekretariat/pool-tanding/' . $row->id_kompetisi_tanding . '/update') ?>" class="row g-3"><?= csrf_field() ?><div class="col-md-3"><label class="form-label">Nomor Pool</label><input class="form-control" name="nomor_pool" value="<?= esc((string) ($row->nomor_pool ?? '')) ?>"></div><div class="col-md-3"><label class="form-label">Max Peserta</label><input class="form-control" type="number" name="max_peserta" value="<?= esc((string) ($row->max_peserta ?? 0)) ?>"></div><div class="col-md-3"><label class="form-label">Perhitungan Medali</label><select class="form-select" name="perhitungan_medali"><option value="1" <?= (int) ($row->perhitungan_medali ?? 0) === 1 ? 'selected' : '' ?>>Ya</option><option value="0" <?= (int) ($row->perhitungan_medali ?? 0) === 0 ? 'selected' : '' ?>>Tidak</option></select></div><div class="col-md-12"><label class="form-label">Keterangan</label><textarea class="form-control" name="keterangan" rows="2"><?= esc($row->keterangan ?? '') ?></textarea></div><div class="col-12"><button class="btn btn-admin-brand rounded-pill">Simpan</button></div></form></section>
<section class="admin-card">
    <ul class="nav nav-pills nav-fill mb-4" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#baganTanding" type="button">Bagan</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#pertandinganTanding" type="button">Daftar Pertandingan</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#pesertaTanding" type="button">Peserta Pool</button></li></ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="baganTanding"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><h4 class="h5 mb-0">Bagan Pertandingan</h4><div class="d-flex flex-wrap gap-2"><form method="post" action="<?= base_url('admin/sekretariat/pool-tanding/' . $row->id_kompetisi_tanding . '/acak-bagan') ?>" onsubmit="return confirm('Acak ulang dengan formula? Bagan lama yang belum dijadwalkan akan diganti.')"><?= csrf_field() ?><input type="hidden" name="mode" value="formula"><button class="btn btn-sm btn-outline-danger rounded-pill" type="submit">Shuffle Formula</button></form><form method="post" action="<?= base_url('admin/sekretariat/pool-tanding/' . $row->id_kompetisi_tanding . '/acak-bagan') ?>" onsubmit="return confirm('Acak ulang full random + Persilat? Bagan lama yang belum dijadwalkan akan diganti.')"><?= csrf_field() ?><input type="hidden" name="mode" value="full_random_persilat"><button class="btn btn-sm btn-danger rounded-pill" type="submit">Full Random Persilat</button></form><a class="btn btn-sm btn-outline-danger rounded-pill" href="<?= base_url('admin/sekretariat/pool-tanding/' . $row->id_kompetisi_tanding . '/bagan.pdf') ?>" target="_blank">Cetak Bagan</a></div></div><?php if (! empty($row->bagan_pertandingan)) : ?><?= view('shared_components/kompetisi_tanding/bagan_pertandingan', ['kompetisi_tanding' => $row, 'toggle_early_match' => false]) ?><?php else : ?><p class="muted-copy mb-0">Bagan belum tersedia. Drawing belum dilakukan.</p><?php endif; ?></div>
        <div class="tab-pane fade" id="pertandinganTanding"><div class="table-responsive"><table class="table admin-table admin-datatable-export align-middle mb-0"><thead><tr><th>Babak</th><th>No</th><th>Merah</th><th>Biru</th><th>Partai</th><th>Gelanggang</th><th>Tanggal</th><th class="text-end no-export">Aksi</th></tr></thead><tbody><?php foreach (($pertandinganRows ?? []) as $match) : ?><tr><td><?= esc($match->babak ?? '-') ?></td><td><?= esc((string) ($match->nomor_pertandingan ?? '-')) ?></td><td><?= esc(($match->nama_atlet_merah ?? '-') . ' / ' . ($match->nama_kontingen_merah ?? '-')) ?></td><td><?= esc(($match->nama_atlet_biru ?? '-') . ' / ' . ($match->nama_kontingen_biru ?? '-')) ?></td><td><?= esc((string) ($match->nomor_partai ?? '-')) ?></td><td><?= esc($match->nama_gelanggang ?? '-') ?></td><td><?= esc($match->tanggal ?? '-') ?></td><td class="text-end"><a class="btn btn-sm btn-outline-danger rounded-pill" href="<?= base_url('admin/sekretariat/pertandingan-tanding/' . $match->id_pertandingan) ?>">Detail</a></td></tr><?php endforeach; ?></tbody></table></div></div>
        <div class="tab-pane fade" id="pesertaTanding"><div class="table-responsive"><table class="table admin-table admin-datatable-export align-middle mb-0"><thead><tr><th>Nama</th><th>Kontingen</th></tr></thead><tbody><?php foreach (($peserta ?? []) as $item) : ?><tr><td><?= esc($item->nama_pendaftar ?? '-') ?></td><td><?= esc($item->nama_kontingen ?? '-') ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    </div>
</section>
<?= $this->endSection() ?>
