<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<section class="admin-card"><div class="d-flex justify-content-between align-items-center gap-3 mb-4"><div><p class="eyebrow mb-1">Kategori Seni</p><h3 class="section-title h4 mb-0"><?= esc($row->nama_seni ?? '-') ?></h3></div><a class="btn btn-outline-secondary rounded-pill" href="<?= base_url('admin/sekretariat/kategori-seni') ?>">Kembali</a></div><div class="table-responsive"><table class="table table-sm admin-table align-middle mb-0"><tbody><tr><th class="text-muted fw-medium">Kategori Usia</th><td><?= esc($row->nama_kategori_usia ?? '-') ?></td><th class="text-muted fw-medium">Jenis Kelamin</th><td><?= esc($row->jenis_kelamin ?? '-') ?></td><th class="text-muted fw-medium">Jenis Seni</th><td><?= esc($row->jenis_seni ?? '-') ?></td></tr><tr><th class="text-muted fw-medium">Jenis Perlombaan</th><td><?= esc($row->jenis_perlombaan ?? '-') ?></td><th class="text-muted fw-medium">Sistem Penampilan</th><td><?= esc($row->sistem_penampilan ?? '-') ?></td><th class="text-muted fw-medium">Konfigurasi Peserta</th><td><?= esc((string) ($row->jumlah_peserta ?? '-')) ?></td></tr><tr><th class="text-muted fw-medium">Kelompok</th><td><?= esc((string) ($row->jumlah_kelompok_peserta_seni ?? 0)) ?> / <?= esc((string) ($row->total_kapasitas_kelompok_peserta_seni ?? 0)) ?></td><th class="text-muted fw-medium">Jumlah Pool</th><td><?= esc((string) ($row->jumlah_pool ?? 0)) ?></td><th class="text-muted fw-medium">Partai Battle</th><td><?= esc((string) ($row->jumlah_partai_battle_seni ?? 0)) ?></td></tr><tr><th class="text-muted fw-medium">Keterangan</th><td colspan="5"><?= esc($row->keterangan ?? '-') ?></td></tr></tbody></table></div></section>
<section class="admin-card mt-4">
    <ul class="nav nav-pills nav-fill mb-4" role="tablist">
        <li class="nav-item" role="presentation"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#daftarPoolSeni" type="button" role="tab">Daftar Pool</button></li>
        <li class="nav-item" role="presentation"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#daftarPesertaSeni" type="button" role="tab">Daftar Peserta</button></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="daftarPoolSeni" role="tabpanel">
            <div class="admin-table-wrap"><div class="table-shell admin-table-scroller"><table class="table admin-table admin-datatable align-middle mb-0">
                <thead><tr><th>Kategori Usia</th><th>Jenis Kelamin</th><th>Jenis Seni</th><th>Nama Seni</th><th>Jumlah Peserta</th><th>Max Peserta</th><th>Nomor Pool</th><th>Keterangan</th><th class="text-end">Aksi</th></tr></thead>
                <tbody><?php foreach (($poolRows ?? []) as $pool) : ?><tr><td><?= esc($pool->nama_kategori_usia ?? '-') ?></td><td class="text-capitalize"><?= esc($pool->jenis_kelamin ?? '-') ?></td><td><?= esc($pool->jenis_seni ?? '-') ?></td><td><?= esc($pool->nama_seni ?? '-') ?></td><td class="text-end"><?= esc((string) ($pool->jumlah_kelompok_peserta_seni ?? 0)) ?></td><td class="text-end"><?= esc((string) ($pool->max_peserta ?? 0)) ?></td><td class="text-end"><?= esc((string) ($pool->nomor_pool ?? '-')) ?></td><td><?= esc($pool->keterangan_kompetisi_seni ?? '-') ?></td><td class="text-end"><div class="dropdown"><button class="btn btn-sm btn-outline-danger rounded-pill dropdown-toggle" type="button" data-bs-toggle="dropdown">Aksi</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="<?= base_url('admin/sekretariat/pool-seni/' . $pool->id_kompetisi_seni) ?>">Lihat Pool</a></li><li><a class="dropdown-item" href="<?= base_url('admin/sekretariat/pool-seni/' . $pool->id_kompetisi_seni) ?>">Edit Pool</a></li><li><span class="dropdown-item disabled">Cetak Statistik Battle belum tersedia</span></li><li><span class="dropdown-item disabled">Hapus pool belum dimigrasikan</span></li></ul></div></td></tr><?php endforeach; ?></tbody>
            </table></div></div>
        </div>
        <div class="tab-pane fade" id="daftarPesertaSeni" role="tabpanel">
            <div class="admin-table-wrap"><div class="table-shell admin-table-scroller"><table class="table admin-table admin-datatable align-middle mb-0">
                <thead><tr><th>Anggota</th><th>Kontingen</th><th>Kategori</th><th>Jurus</th><th>Pool</th><th>Nomor Undi</th><th>Pembayaran</th><th>Keterangan</th><th class="text-end">Aksi</th></tr></thead>
                <tbody><?php foreach (($kelompokRows ?? []) as $kelompok) : ?><tr><td class="fw-semibold text-capitalize"><?= esc($kelompok->anggota_kelompok_peserta_seni ?? '-') ?></td><td><?= esc($kelompok->nama_kontingen ?? '-') ?></td><td><?= esc(($kelompok->nama_kategori_usia ?? '-') . ' ' . ($kelompok->jenis_kelamin ?? '')) ?></td><td><?= esc(($kelompok->jenis_seni ?? '-') . ' - ' . ($kelompok->nama_seni ?? '-')) ?></td><td class="text-end"><?= esc((string) ($kelompok->nomor_pool ?? '-')) ?></td><td class="text-end"><?= ($kelompok->sistem_penampilan ?? '') === 'pool' ? esc((string) ($kelompok->nomor_undi ?? '-')) : '<i>Tidak ada undian</i>' ?></td><td><?= esc($kelompok->status_pembayaran ?? 'belum lunas') ?></td><td><?= esc($kelompok->keterangan ?? '-') ?></td><td class="text-end"><div class="dropdown"><button class="btn btn-sm btn-outline-danger rounded-pill dropdown-toggle" type="button" data-bs-toggle="dropdown">Aksi</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="<?= base_url('admin/sekretariat/pool-seni/' . $kelompok->id_kompetisi_seni) ?>">Lihat Bagan</a></li><li><a class="dropdown-item" href="<?= base_url('admin/sekretariat/kelompok-seni/' . $kelompok->id_kelompok_peserta_seni) ?>">Ganti Atlet / Kategori</a></li><li><a class="dropdown-item" href="<?= base_url('admin/sekretariat/kelompok-seni/' . $kelompok->id_kelompok_peserta_seni) ?>">Pindah Pool</a></li><li><hr class="dropdown-divider"></li><li><form method="post" action="<?= base_url('admin/sekretariat/kelompok-seni/' . $kelompok->id_kelompok_peserta_seni . '/delete') ?>" onsubmit="return confirmAdminAction(this, 'Undurkan kelompok?', 'Kelompok seni ini akan dihapus dari kategori.', 'Undur Diri')"><?= csrf_field() ?><button class="dropdown-item text-danger" type="submit">Undur Diri</button></form></li></ul></div></td></tr><?php endforeach; ?></tbody>
            </table></div></div>
        </div>
    </div>
</section>
<?= $this->endSection() ?>
